### ISSUE TITLE
Alias filetype

### ISSUE THREAD

**Issue by alcohol** [fkfk/vim-modeline#4]
Is it possible to make modeline detect `filetype=make` as `makefile`? Cause vim and Atom do not align on the filetype here, and so the modeline plugin does not apply the correct language syntax :/

**Comment by fkfk** [comment]
I have fixed the problem in the v0.5.0.
Please update vim-modeline.

**Comment by alcohol** [comment]
Can confirm that it works. Thank you for the swift response :-)
